### ISSUE TITLE
Not able to load information: DataSource.Error ContentRype not supported

### ISSUE THREAD

**Issue by Rlima999** [fortify-ps/FortifyPowerQueryConnectors#2]
Hi,

I'm trying to connect fortify to Power BI.
I added it the plugin fortify ssc (beta) but on navigator tab when try to select the option to extract information the Power BI is given me the error: 
"DataSource.Error: Type of contente not support.
Details:
    DataSourceKind=FortifySSC
    DataSourcePath=FortifySSC
    ContentType=text/html"

I already add extension html content but issue persist.

How can i extract the information?

Regards,

Rui
<img width="631" alt="pbi" src="https://user-images.githubusercontent.com/32990367/212359466-8c142822-2ff5-4928-a33d-c7c2682c8be9.PNG">

**Comment by MikeTheSnowman** [comment]
Hey @Rlima999, apologies for the delay. From the screenshot that you've sent, it looks like you're calling an API that performs rulepack updates. Do you get the same error with the other APIs?

**Comment by Rlima999** [comment]
Hi,

Thanks for reply.

Yes, same error. I enter SSC and CLI token as request.

<img width="708" alt="powerbi" src="https://user-images.githubusercontent.com/32990367/213439409-3673fcba-30a5-4517-bb8b-a9adf79e6831.PNG">

**Comment by MikeTheSnowman** [comment]
> Hi,
> 
> Thanks for reply.
> 
> Yes, same error. I enter SSC and CLI token as request.
> 
> <img width="708" alt="powerbi" src="https://user-images.githubusercontent.com/32990367/213439409-3673fcba-30a5-4517-bb8b-a9adf79e6831.PNG">
> 

Hey @Rlima999 . The Micro Focus support person should have sent you my contact information. Send me an email and we can have a screen sharing if you're up for it.

**Comment by MikeTheSnowman** [comment]
Hey @Rlima999. I've just created a new updated connector. Can you give it a try and let me know if it resolves your issue?

**Comment by MikeTheSnowman** [comment]
Closing the issue, but leaving some additional information for others who happen to come across this issue.

- First, make sure that you're using v0.4  or higher
- Make sure that the URL to the SSC server that you provide doesn't contain a trailing `/` character at the end of the url. I'll look to update the connector so that it won't care about this.
- Make sure that after you create the connection, you go back and edit the connection to set the `privacy level` to `public`.
<img width="343" alt="2023-02-06 21_48_05-Rui Lima (External) _ Microsoft Teams" src="https://user-images.githubusercontent.com/5297545/216957780-50d1f1c1-32fe-4297-b680-e6a407785f89.png">
