### ISSUE TITLE
Issue - FortifyPowerQueryConnectors - Cyclically defined type can not be created Details: through Power BI

### ISSUE THREAD

**Issue by maamirkhan192** [fortify-ps/FortifyPowerQueryConnectors#4]
Hi All

when i parameter values under 3 fields from "listprojectversion" and add on Projectversion.name, Project.name and InstanceId in listIssueDetails I get below error

Expression.Error: Cyclically defined type can not be created
Details:
    type=object
    required=[List]
    properties=[Record]
    description=Issue analysis trace node DTO.

Please note Same thing  I check swagger it's working fine. but through Power BI I am getting above error

Any one can help me on this issue.

**Comment by maamirkhan192** [comment]
@wtfacoconut   Any update on the above issue

**Comment by MikeTheSnowman** [comment]
> @wtfacoconut   Any update on the above issue

Hey @maamirkhan192 , apologies for the delay reply. Work towards the end of the year and some sudden changes in my personal life are eating up huge amounts of time at the moment.

First, I was able to replicate the same issues as you. I'm not sure why, but powerbi is not properly generating the query parameter.

Not quite sure how to address this, but this is not the only issue where I won't be able to directly fix the issue as I'm currently relying on powerbi to auto generate the query parameter fields from SSC's swagger file.

I had been in the process of creating a new and improved powerbi connector to address these and other issues, but I won't have an update until after Christmas. 

I'm currently in the process of changing homes, hence the delay.

**Comment by maamirkhan192** [comment]
@wtfacoconut how to resolved the issue  its bit urgent 

when i parameter values under 3 fields from "listprojectversion" and add on Projectversion.name, Project.name and InstanceId in listIssueDetails I get below error

Expression.Error: Cyclically defined type can not be created
Details:
type=object
required=[List]
properties=[Record]
description=Issue analysis trace node DTO.

**Not working in Power BI**
![Screenshot 2023-11-21 012110](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/149720534/874e9601-80c4-46ce-be10-eba1b8762950)

**Its working fine in Swagger UI** 
![Screenshot 2023-11-21 012637](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/149720534/8a384219-18f0-4b22-a275-fdb5066dd80c)

**Comment by MikeTheSnowman** [comment]
Hey @maamirkhan192. Just a quick update. I'm still investigating, but I think I know what the issue is now.
The issue is that the SSC swagger spec json file has a cyclical reference with the tracenode attribute.

Just for insight, here's the cyclical referency in the the `spec.json` file that Fortify SSC is returning to the Power BI connector:

![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/d8931b61-fde4-4f33-80a3-1566a8c26e62)

Now, the question as to how this issue can be fixed, there are a few ways:

1. The Fortify SSC engineers will need to update the `spec.json` to not have that cyclical reference 
  - Pro: This will be a long term fix.
  - Con: This won't address the issue immediately for your version of Fortify SSC (only potentially the next version) and we could be waiting a while.
2. I could embedd a modified copy of the `spec.json` file in the power query connector that removes the cyclic reference
  - Pro: This could result in addressing the issue faster
  - Con: The power query connector could become version locked to a specific version of SSC. Right now, the connector pulls the `spec.json` file from a user's desired Fortify SSC server (which can be any version) in order to auto generate all the quert functions and parameters.


For now, I'll try to do a quick test with embedding a modified copy of the `spec.json` file in the connector. I'll let you know how the test goes by tomorrow.

**Comment by MikeTheSnowman** [comment]
@maamirkhan192 . I've created a new release v0.4.1 ([link to release](https://github.com/fortify-ps/FortifyPowerQueryConnectors/releases/tag/v0.4.1-beta)) to address your issue. Please see my instructions/screenshots below:

Provide parameters as you did in Swagger:
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/b917e4c6-c182-4d3c-956c-c1f05d3e3385)

Then click on "table":
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/651b60a5-1603-4e34-9a62-06802caab84b)

Delete all colums with "error":
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/7f315a82-c55c-410f-80f3-ae6d4ac378f8)

Delete the "traceNodes" column:
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/39f2f8ac-6667-4303-b702-def110d401c2)


If you see an error, just ignore it:
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/e84b1db5-fec4-41fe-b965-1aff25550084)

Quick test table to show the data that came from that query:
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/95adc928-1438-45f5-b7b6-f469fb22b04f)

**Comment by maamirkhan192** [comment]
Hi @wtfacoconut thanks and can you please share the file FortifyConnector.mez so that I can replace that .

How you generate the .mez file

**Comment by MikeTheSnowman** [comment]
@maamirkhan192 , please see the link I provided to you and my previous comment. I've already generated the MEZ file for you in the release.

**Comment by maamirkhan192** [comment]
@wtfacoconut how to parameterized this I have a lot project name , Project version and IntanceId in power bi
et
    Source = FortifyConnector.FortifySSC(),
    listIssueDetail1 = Source{[Name="listIssueDetail"]}[Data],
    #"Invoked FunctionlistIssueDetail1" = listIssueDetail1("**ASCENT**", "**ASCENT-TPCP-1.0**", "**ad5ee2ee-cde3-2a1b-8810-a09c6168dc9f**"),
    data = #"Invoked FunctionlistIssueDetail1"[data]
in
    data

**Comment by MikeTheSnowman** [comment]
@maamirkhan192 , can you maybe elaborate a bit more on what you're trying to accomplish for your Power BI report?

**Comment by maamirkhan192** [comment]
@wtfacoconut 

As there are multiple Project and and Project version and Instance DI so I want to extract the data at once for the multiple project's. I don't want to extract the table one by one every time

![Screenshot 2023-11-21 200756](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/149720534/6ac1d4e4-cc45-4ec0-b28c-2025ea9587db)

**Comment by MikeTheSnowman** [comment]
@maamirkhan192 , I'm not a Power BI expert, but here's what I came up with. I've also included an example report for you to take a look at.
[Example SSC Report with App and AppVersion Names Parameterized.zip](https://github.com/fortify-ps/FortifyPowerQueryConnectors/files/13428038/Example.SSC.Report.with.App.and.AppVersion.Names.Parameterized.zip)

Example table output from a query that uses parameters. I'll show you what happens when I update the parameters. After updating the parameters, the table output will change.
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/435e8e23-677b-4d45-8208-08a93e402dd1)

There are technically three parameters. We modify the `ApplicationName` and `ApplicationVersionName` parameters which then effect the `projectVersionId` that gets populated into the `ApplicationVersionId` parameter.
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/186d503e-a77b-40fa-a0c3-c4e3f9e953c4)

Notice the `ApplicationVersionId` parameter and `ApplicationVersionIssues` query break when I change the value in `ApplicationName`. This is because we still need to update the `ApplicationVersionName` parameter.
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/7b6d5ad0-58a9-42ce-af35-9cd57d0cdd33)

Modifying the `ApplicationVersionName` parameter to a name that actually exists within the Application in SSC results in the correct `ApplicationVersionId` being found and auto-populated into the parameter.

![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/e38cc331-34e5-4edc-8f98-2a07df7a67f4)
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/fca99db3-bc2a-4aec-8eac-324347c5c876)

The data now correctly populates in the query. In the `Advanced Editor` we can see the parameter.
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/4a33af93-a7db-4e44-a7ec-a96a974e595f)
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/6e717cf3-6d00-45d6-8f09-4d87b4255ca6)

Finally, you can see the table in the report updates with new info after we've sucessfully updated the parameters.
![image](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/5297545/fcf63b1f-a839-47f9-ae22-7e49a509d5db)

**Comment by maamirkhan192** [comment]
@wtfacoconut I am bit confused on your example. it will be good if you used  listIssueDetail for Projectversion.name, Project.name and InstanceId in listIssueDetails

![284470775-b917e4c6-c182-4d3c-956c-c1f05d3e3385](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/149720534/180498e0-bdfb-41f4-b6eb-f7e87ce3602f)

**Comment by MikeTheSnowman** [comment]
@maamirkhan192 , the query that you're running with `listIssueDetails` will only provide you information for a single issue/vulnerability from an Application Version. 

I assume that you want information for more than one issue right?

**Comment by MikeTheSnowman** [comment]
@maamirkhan192 , it looks like the original technical problem that you raised in this issue has been resolved. 

Can I ask that you please create a new issue for your issue about parameters?

I'd like to close this issue as the conversation now is no longer about the original problem.

**Comment by MikeTheSnowman** [comment]
@maamirkhan192 , I'm closing this issue now as I believe that we've addressed the original problem that you raised.
